name = "EkaiiPlus"
author = "EkaiiMC"
version = "1.21.4-1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5662c7e8dd8d739bf575753021d76c8dc98c3a03f25e1d2b36517dd10c86281b"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = []
