name = "EkaiiPlus"
author = "EkaiiMC"
version = "1.21-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2380a97007ea582cb22480602bfcb682ea6ec7ac7edb97b96d57f4650ab2afd"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.20", "1.20.1", "1.20.2", "1.20.3", "1.20.4", "1.20.5", "1.20.6"]
