name = "EkaiiPlus"
author = "EkaiiMC"
version = "1.21.1-1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ceea9f9e75d0ddece7ff2ead30c00797bf1f2645e0d221aca351a3f327fa9fad"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = []
