#AutomaticMemories config
#Sat Sep 14 02:53:05 CEST 2024
interval_ms=10800000
leftover_interval_ms=8239025
notify_player=false
require_in_world=true
require_unpaused=false
restart_timer_each_session=false
save_directory=screenshots
screenshot_prefix=auto_
