#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Mar 16 22:40:57 CET 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=8
shaderPack=Bliss-Shader-Ekaii.zip
