#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Sep 14 02:52:38 CEST 2024
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=12
shaderPack=ComplementaryReimagined_r5.2.2 (renew) (ekaii) + EuphoriaPatches_1.3.2
