maxPlayers=8 #               Max amount of re-joins per client. | default: 8
autoWhitelist=true #         Automatically whitelist if whitelist is enabled. | default: true
autoOp=true #                Automatically op if original client is also op. | default: true
spawnNearPlayer=true #       Spawn near the player, if false new players will join at world spawn. | default: true
spawnNearPlayerRadius=10 #   If spawnNearPlayer is enabled, this will set the radius on who close the player should spawn. | default: 10
copyTexture=true #           Copy the texture of the original player. | default: true
prefixWithNumber=true #      Adds a `$_` prefix to the username (Highly recommended to keep on true) | default: true

